### ISSUE TITLE
Missing `large-example` code

### ISSUE THREAD

**Issue by dliu120** [jherr/practical-module-federation-20#5]
The Practical Module Federation book references a `large-example` directory (page 167), but I don't see it in this repository. Am I missing something?

![CleanShot 2024-01-04 at 11 18 37@2x](https://github.com/jherr/practical-module-federation-20/assets/2090090/98c5c037-7653-4872-b961-7e7d27315920)

**Comment by jherr** [comment]
Apologies. Here is the repo for that example: https://github.com/jherr/wp5-full-site-federation/tree/master
